"""empty message

Revision ID: 6b4fce943049
Revises: 25f932070e1f
Create Date: 2024-08-01 00:37:13.124617

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b4fce943049'
down_revision = '25f932070e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('hair_color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('skin_color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('eye_color', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('birth_year', sa.String(length=200), nullable=True))
        batch_op.drop_column('weight')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('orbital_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('surface_water', sa.Integer(), nullable=True))
        batch_op.alter_column('gravity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=200),
               existing_nullable=True)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_class', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('cost_in_credits', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('length', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('crew', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('passengers', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('max_atmosphering_speed', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cargo_capacity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('consumables', sa.String(length=50), nullable=True))
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('capacity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('capacity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('consumables')
        batch_op.drop_column('cargo_capacity')
        batch_op.drop_column('max_atmosphering_speed')
        batch_op.drop_column('passengers')
        batch_op.drop_column('crew')
        batch_op.drop_column('length')
        batch_op.drop_column('cost_in_credits')
        batch_op.drop_column('vehicle_class')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('gravity',
               existing_type=sa.String(length=200),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('surface_water')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('rotation_period')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('birth_year')
        batch_op.drop_column('eye_color')
        batch_op.drop_column('skin_color')
        batch_op.drop_column('hair_color')
        batch_op.drop_column('mass')

    # ### end Alembic commands ###
